import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#033236',
  canvas: '#FFFFFF',
  parchment: '#F6F6F6',
  ink: '#1D1D1F',
  inkMuted48: '#7A7A7A',
  hairline: 'rgba(0,0,0,0.08)',
  hairlineSolid: 'rgba(0,0,0,0.15)',
  gold: '#C9A227',
  goldTint: '#FDF6E3',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.canvas },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 4,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  logoBadge: {
    width: 30, height: 30, borderRadius: 9,
    backgroundColor: COLORS.primary,
    alignItems: 'center', justifyContent: 'center',
  },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  content: {
    paddingHorizontal: 24,
    paddingTop: 24,
    paddingBottom: 16,
    gap: 22,
  },
  title: {
    fontSize: 24,
    fontWeight: '600',
    color: COLORS.ink,
    lineHeight: 32,
  },
  subLabel: { fontSize: 13, color: COLORS.inkMuted48, marginTop: 8 },
  sectionLabel: { fontSize: 13, fontWeight: '500', color: COLORS.inkMuted48 },
  input: {
    height: 48,
    backgroundColor: COLORS.parchment,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: COLORS.ink,
  },
  textarea: {
    height: 96,
    paddingVertical: 12,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    width: '47.5%',
    height: 48,
    borderWidth: 1,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  rowChip: {
    flex: 1,
    height: 48,
    borderWidth: 1,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  noticeCard: {
    backgroundColor: COLORS.goldTint,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  noticeText: { fontSize: 13, color: COLORS.gold, fontWeight: '600', textAlign: 'center' },
  rewardBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: COLORS.canvas,
    borderRadius: 9999,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  rewardBadgeLabel: { fontSize: 13, fontWeight: '700', color: COLORS.gold },
  rewardBadgeValue: { fontSize: 13, fontWeight: '700', color: COLORS.ink },
  footer: { paddingHorizontal: 24, paddingBottom: 24, paddingTop: 8 },
  submitButton: {
    height: 50,
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: { fontSize: 17, fontWeight: '600' },
});
