import { StyleSheet } from 'react-native';
import { COLORS } from '../../../shared/디자인/tokens';


export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 10 },
  logoBadge: { width: 30, height: 30, borderRadius: 9, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  content: { paddingHorizontal: 24, paddingTop: 10, paddingBottom: 24, gap: 18 },
  title: { fontSize: 22, fontWeight: '700', color: COLORS.ink },
  subtitle: { fontSize: 13, color: COLORS.inkMuted48, marginTop: 2 },
  mapCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 18, padding: 16, gap: 10 },
  cardHeader: { fontSize: 13, fontWeight: '700', color: COLORS.ink },
  mapHint: { fontSize: 11.5, color: COLORS.inkMuted48, textAlign: 'center' },
  podiumCard: { backgroundColor: COLORS.goldTint, borderRadius: 18, padding: 16, gap: 14 },
  podiumHeader: { fontSize: 12, fontWeight: '700', color: COLORS.gold },
  podiumRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', gap: 10 },
  podiumBadge: { width: 44, height: 44, borderRadius: 9999, alignItems: 'center', justifyContent: 'center' },
  podiumBadgeText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  podiumName: { fontSize: 13, fontWeight: '700', color: COLORS.ink },
  podiumScore: { fontSize: 11.5, fontWeight: '700', color: COLORS.primary },
  podiumBar: { width: 64, borderRadius: 8, opacity: 0.85 },
  myRegionRow: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14, borderRadius: 14, backgroundColor: COLORS.primary },
  myRegionBadge: { width: 34, height: 34, borderRadius: 9999, backgroundColor: 'rgba(255,255,255,0.16)', alignItems: 'center', justifyContent: 'center' },
  myRegionBadgeText: { color: '#fff', fontSize: 13, fontWeight: '700' },
  myRegionLabel: { fontSize: 11, fontWeight: '600', color: 'rgba(255,255,255,0.65)' },
  myRegionName: { fontSize: 14.5, fontWeight: '700', color: '#fff' },
  myRegionScore: { fontSize: 14, fontWeight: '700', color: '#fff' },
  listHeader: { fontSize: 13, fontWeight: '700', color: COLORS.ink },
  rankRow: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, paddingHorizontal: 14, borderRadius: 14, borderWidth: 1 },
  rankBadge: { width: 28, height: 28, borderRadius: 9999, alignItems: 'center', justifyContent: 'center' },
  rankBadgeText: { fontSize: 13, fontWeight: '700' },
  rankName: { fontSize: 14.5, fontWeight: '700', color: COLORS.ink },
  mineTag: { fontSize: 10, fontWeight: '700', color: COLORS.primary, backgroundColor: COLORS.goldTint, paddingVertical: 2, paddingHorizontal: 7, borderRadius: 9999 },
  mineTagText: { fontSize: 10, fontWeight: '700', color: COLORS.primary },
  rankScore: { fontSize: 14, fontWeight: '700', color: COLORS.primary },
});
