import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#033236',
  canvas: '#FFFFFF',
  parchment: '#F6F6F6',
  ink: '#1D1D1F',
  inkMuted48: '#7A7A7A',
  inkMuted80: '#333333',
  hairline: 'rgba(0,0,0,0.08)',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.canvas },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoBadge: {
    width: 30, height: 30, borderRadius: 9,
    backgroundColor: COLORS.primary,
    alignItems: 'center', justifyContent: 'center',
  },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  content: {
    paddingHorizontal: 24,
    paddingTop: 28,
    gap: 28,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: COLORS.ink,
    lineHeight: 36,
  },
  allAgreeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    backgroundColor: COLORS.parchment,
    borderRadius: 18,
  },
  allAgreeText: { fontSize: 17, fontWeight: '600', color: COLORS.ink },
  divider: { height: 1, backgroundColor: COLORS.hairline },
  termRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 4,
  },
  termLabel: { fontSize: 17, color: COLORS.ink },
  termView: { fontSize: 14, color: COLORS.inkMuted48, textDecorationLine: 'underline' },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  nextButton: {
    height: 50,
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextButtonText: { fontSize: 17, fontWeight: '600' },
  sheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  sheet: {
    maxHeight: '70%',
    backgroundColor: COLORS.canvas,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    gap: 14,
  },
  modalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  modalCard: {
    width: '100%',
    maxHeight: '100%',
    backgroundColor: COLORS.canvas,
    borderRadius: 18,
    padding: 24,
    gap: 14,
  },
  modalButton: {
    height: 44,
    borderRadius: 9999,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalButtonText: { fontSize: 17, fontWeight: '600', color: COLORS.canvas },
  sheetHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  sheetTitle: { fontSize: 17, fontWeight: '600', color: COLORS.ink, flex: 1 },
  sheetBody: { fontSize: 14, lineHeight: 22, color: COLORS.inkMuted80 },
});
