import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#033236',
  canvas: '#FFFFFF',
  parchment: '#F6F6F6',
  ink: '#1D1D1F',
  inkMuted48: '#7A7A7A',
  hairline: 'rgba(0,0,0,0.08)',
  gold: '#C9A227',
  goldTint: '#FDF6E3',
  mint: '#8BD19D',
};
export const RADIUS = { lg: 18, pill: 9999 };
export const TYPE = {
  display: { fontSize: 22, fontWeight: '600', letterSpacing: -0.3 },
  body: { fontSize: 17, letterSpacing: -0.37 },
  caption: { fontSize: 14, letterSpacing: -0.22 },
  micro: { fontSize: 10 },
};

export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 8 },
  logoBadge: { width: 30, height: 30, borderRadius: 9, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  burgerLine: { width: 22, height: 2, borderRadius: 1, backgroundColor: COLORS.ink },
  content: { paddingHorizontal: 24, paddingTop: 20, paddingBottom: 12, gap: 24 },
  rowSectionTitle: { fontSize: 15, fontWeight: '600', letterSpacing: -0.22, color: COLORS.ink },
  carouselRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  activeCardOuter: { borderRadius: 19, padding: 2 },
  activeCardShell: { borderRadius: 17, overflow: 'hidden' },
  activeCardContent: { padding: 12, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', gap: 10 },
  activeCardIconBadge: { width: 32, height: 32, borderRadius: 9999, backgroundColor: 'rgba(255,255,255,0.14)', alignItems: 'center', justifyContent: 'center' },
  activeStatusLabel: { fontSize: 10.5, fontWeight: '700', letterSpacing: 0.5 },
  activeCardTitle: { fontSize: 14.5, letterSpacing: -0.22, fontWeight: '700' },
  sectionTitleLg: { ...TYPE.display, color: COLORS.ink },
  questRow: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: 'rgba(255,255,255,0.5)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.7)', borderRadius: 18, paddingVertical: 14, paddingHorizontal: 18 },
  questRowIconBadge: { width: 36, height: 36, borderRadius: 9999, backgroundColor: 'rgba(139,209,157,0.3)', alignItems: 'center', justifyContent: 'center' },
  questRowTitle: { ...TYPE.body, color: COLORS.ink, fontWeight: '600', flex: 1 },
  detailButton: { height: 32, paddingHorizontal: 14, borderRadius: RADIUS.pill, backgroundColor: 'rgba(255,255,255,0.8)', borderWidth: 1, borderColor: 'rgba(0,0,0,0.06)', alignItems: 'center', justifyContent: 'center' },
  detailButtonText: { ...TYPE.caption, color: COLORS.ink, fontWeight: '600' },
  reRollButton: { height: 44, borderRadius: RADIUS.lg, backgroundColor: 'rgba(255,255,255,0.3)', borderWidth: 1, borderColor: 'rgba(0,0,0,0.06)', alignItems: 'center', justifyContent: 'center' },
  reRollButtonText: { ...TYPE.caption, color: COLORS.inkMuted48, fontWeight: '600' },
  actionRow: { flexDirection: 'row', gap: 12 },
  actionButton: { flex: 1, height: 48, borderRadius: RADIUS.pill, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  actionButtonText: { ...TYPE.body, color: COLORS.canvas, fontWeight: '600' },
  bottomNav: { flexDirection: 'row', justifyContent: 'space-around', paddingTop: 10, paddingBottom: 20, borderTopWidth: 1, borderTopColor: COLORS.hairline, backgroundColor: 'rgba(255,255,255,0.7)' },
  navItem: { alignItems: 'center', gap: 4, width: 56 },
  navLabel: { ...TYPE.micro, color: COLORS.inkMuted48 },
  menuOverlayRow: { flex: 1, flexDirection: 'row' },
  menuPanel: { width: '78%', maxWidth: 300, paddingTop: 26, paddingHorizontal: 18, paddingBottom: 28 },
  menuHeader: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingTop: 6, marginBottom: 18 },
  menuLogoBadge: { width: 28, height: 28, borderRadius: 8, backgroundColor: 'rgba(255,255,255,0.1)', alignItems: 'center', justifyContent: 'center' },
  menuLogoText: { fontSize: 17, fontWeight: '700', color: '#fff', letterSpacing: -0.3 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 9, paddingHorizontal: 8, borderRadius: 11 },
  sectionTitle: { fontSize: 11, fontWeight: '700', letterSpacing: 1, color: COLORS.mint, textTransform: 'uppercase' },
  menuItemRow: { paddingVertical: 9, paddingHorizontal: 8, paddingLeft: 20, borderRadius: 11 },
  menuItemRowText: { fontSize: 14.5, fontWeight: '600', color: '#fff' },
  menuDivider: { height: 1, backgroundColor: 'rgba(255,255,255,0.12)', marginVertical: 10 },
  menuFooterItem: { paddingVertical: 9, paddingHorizontal: 8, borderRadius: 11 },
  menuFooterItemText: { fontSize: 14, fontWeight: '600', color: 'rgba(255,255,255,0.68)' },
});
