import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#033236',
  canvas: '#FFFFFF',
  parchment: '#F6F6F6',
  ink: '#1D1D1F',
  inkMuted48: '#7A7A7A',
  hairline: 'rgba(0,0,0,0.08)',
  hairlineSolid: 'rgba(0,0,0,0.15)',
  success: '#1F8A5B',
  error: '#C0392B',
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.canvas },
  header: {
    paddingHorizontal: 20,
    paddingTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  logoBadge: {
    width: 30, height: 30, borderRadius: 9,
    backgroundColor: COLORS.primary,
    alignItems: 'center', justifyContent: 'center',
  },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  content: {
    paddingHorizontal: 24,
    paddingTop: 28,
    paddingBottom: 12,
    gap: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: COLORS.ink,
    lineHeight: 36,
  },
  stepLabel: { fontSize: 13, color: COLORS.inkMuted48, marginTop: 8 },
  idRow: { flexDirection: 'row', gap: 8 },
  idInput: {
    flex: 1,
    height: 48,
    backgroundColor: COLORS.parchment,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: COLORS.ink,
  },
  checkButton: {
    height: 48,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: COLORS.hairlineSolid,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.canvas,
  },
  checkButtonText: { fontSize: 13, color: COLORS.ink },
  input: {
    height: 48,
    backgroundColor: COLORS.parchment,
    borderWidth: 1,
    borderColor: COLORS.hairline,
    borderRadius: 14,
    paddingHorizontal: 16,
    fontSize: 15,
    color: COLORS.ink,
  },
  feedback: { fontSize: 13, paddingHorizontal: 4 },
  sectionLabel: { fontSize: 13, fontWeight: '500', color: COLORS.inkMuted48 },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  chip: {
    width: '47.5%',
    height: 48,
    borderWidth: 1,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  footer: { paddingHorizontal: 24, paddingBottom: 24 },
  nextButton: {
    height: 50,
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nextButtonText: { fontSize: 17, fontWeight: '600' },
});
