import { StyleSheet } from 'react-native';
import { COLORS, RADIUS } from '../../../shared/디자인/tokens';


export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 12, flexDirection: 'row', alignItems: 'center', gap: 10, borderBottomWidth: 1, borderBottomColor: COLORS.hairline },
  logoBadge: { width: 30, height: 30, borderRadius: 9, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  content: { padding: 20, gap: 16 },
  profileCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 20, padding: 16 },
  avatar: { width: 60, height: 60, borderRadius: 9999, alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontSize: 22, fontWeight: '700', color: '#fff' },
  nickname: { fontSize: 17, fontWeight: '700', color: COLORS.ink },
  titleTag: { backgroundColor: COLORS.goldTint, borderWidth: 1, borderColor: 'rgba(201,162,39,0.35)', paddingVertical: 3, paddingHorizontal: 9, borderRadius: RADIUS.pill },
  titleTagText: { fontSize: 11, fontWeight: '700', color: COLORS.primary },
  userId: { fontSize: 13, color: COLORS.inkMuted48 },
  level: { fontSize: 12.5, fontWeight: '700', color: COLORS.primary },
  achievementCard: { backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 20, padding: 16, paddingBottom: 14, gap: 10 },
  achievementHeader: { fontSize: 15.5, fontWeight: '700', color: COLORS.ink },
  achievementRow: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 14, padding: 10 },
  achievementIcon: { width: 48, height: 48, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  achievementName: { fontSize: 13.5, fontWeight: '700', color: COLORS.ink },
  achievementDate: { fontSize: 11.5, color: COLORS.inkMuted48 },
  viewButton: { borderWidth: 1, borderColor: COLORS.hairline, backgroundColor: COLORS.parchment, paddingVertical: 8, paddingHorizontal: 11, borderRadius: RADIUS.pill },
  viewButtonText: { fontSize: 11.5, fontWeight: '600', color: COLORS.ink },
  pagination: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', gap: 4, paddingTop: 6 },
  pageDot: { minWidth: 26, height: 26, paddingHorizontal: 4, borderRadius: 9999, alignItems: 'center', justifyContent: 'center' },
  pageDotText: { fontSize: 12.5, fontWeight: '700', color: COLORS.inkMuted48 },
  detailOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32, backgroundColor: 'rgba(3,50,54,0.4)' },
  detailCard: { width: '100%', maxWidth: 290, backgroundColor: '#fff', borderRadius: 22, padding: 20, gap: 14 },
  detailName: { fontSize: 16, fontWeight: '700', color: COLORS.ink },
  divider: { height: 1, backgroundColor: COLORS.hairline },
  detailStory: { fontSize: 13.5, color: COLORS.ink, lineHeight: 20 },
  detailReward: { fontSize: 13, fontWeight: '700', color: COLORS.gold },
  detailCloseButton: { height: 44, borderRadius: RADIUS.pill, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  detailCloseText: { fontSize: 14.5, fontWeight: '600', color: '#fff' },
});
