import { StyleSheet } from 'react-native';
import { COLORS, RADIUS } from '../../../shared/디자인/tokens';


export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: COLORS.ink },
  content: { paddingHorizontal: 24, paddingTop: 14, paddingBottom: 16, gap: 16 },
  title: { fontSize: 20, fontWeight: '700', color: COLORS.ink },
  subtitle: { fontSize: 13, color: COLORS.inkMuted48, marginTop: 2 },
  tabButton: { flex: 1, height: 44, borderRadius: 14, backgroundColor: '#fff', borderWidth: 1, borderColor: 'rgba(3,50,54,0.14)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  tabButtonText: { fontSize: 13.5, fontWeight: '700', color: COLORS.primary },
  dot: { width: 6, height: 6, borderRadius: 9999, backgroundColor: COLORS.gold },
  sectionLabel: { fontSize: 13, fontWeight: '700', color: COLORS.ink },
  countLabel: { fontSize: 12, color: COLORS.inkMuted48 },
  photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  photoTile: { width: '47.5%', aspectRatio: 1, borderRadius: 16, borderWidth: 2, borderColor: 'transparent', backgroundColor: COLORS.parchment, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  photoPlaceholder: { fontSize: 12.5, color: COLORS.inkMuted48, fontWeight: '600' },
  checkBadge: { position: 'absolute', top: 6, right: 6, width: 22, height: 22, borderRadius: 9999, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  photoDateBar: { position: 'absolute', left: 0, right: 0, bottom: 0, paddingVertical: 6, paddingHorizontal: 8, backgroundColor: 'rgba(0,0,0,0.35)' },
  photoDateText: { fontSize: 10.5, fontWeight: '600', color: '#fff' },
  footer: { flexDirection: 'row', gap: 8, paddingHorizontal: 24, paddingBottom: 16 },
  generateButton: { flex: 1, height: 50, borderRadius: RADIUS.pill, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  generateButtonText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  autoButton: { flex: 1, height: 50, borderRadius: RADIUS.pill, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, alignItems: 'center', justifyContent: 'center' },
  autoButtonText: { fontSize: 15, fontWeight: '700', color: COLORS.ink },
  toast: { position: 'absolute', left: '50%', bottom: 96, transform: [{ translateX: -110 }], backgroundColor: COLORS.ink, borderRadius: RADIUS.pill, paddingVertical: 12, paddingHorizontal: 20 },
  toastText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  sheetOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(3,50,54,0.4)' },
  sheet: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 28, gap: 14 },
  sheetHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sheetTitle: { fontSize: 17, fontWeight: '700', color: COLORS.ink },
  scriptInput: { height: 180, borderRadius: 14, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, padding: 14, fontSize: 14, lineHeight: 21, color: COLORS.ink },
  saveButton: { height: 48, borderRadius: RADIUS.pill, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  saveButtonText: { fontSize: 14.5, fontWeight: '700', color: '#fff' },
  trackRow: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, paddingHorizontal: 14, borderRadius: 16, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: 'transparent' },
  trackName: { fontSize: 14, fontWeight: '700', color: COLORS.ink },
  trackDesc: { fontSize: 11.5, color: COLORS.inkMuted48 },
  previewLink: { fontSize: 11.5, fontWeight: '600', color: COLORS.primary, marginTop: 2 },
  selectTrackButton: { height: 34, paddingHorizontal: 16, borderRadius: RADIUS.pill, backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, alignItems: 'center', justifyContent: 'center' },
  selectTrackText: { fontSize: 12.5, fontWeight: '700', color: COLORS.ink },
});
