import { StyleSheet } from 'react-native';
import { COLORS, RADIUS } from '../../../shared/디자인/tokens';


export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 8 },
  logoBadge: { width: 30, height: 30, borderRadius: 9, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  content: { paddingHorizontal: 24, paddingTop: 18, paddingBottom: 16, gap: 20 },
  profileCard: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 18, padding: 14, paddingHorizontal: 16 },
  avatar: { width: 52, height: 52, borderRadius: 9999, backgroundColor: COLORS.mint, alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontSize: 17, fontWeight: '700', color: '#fff' },
  nickname: { fontSize: 16, fontWeight: '700', color: COLORS.ink },
  titleTag: { backgroundColor: COLORS.goldTint, borderWidth: 1, borderColor: 'rgba(201,162,39,0.5)', paddingVertical: 3, paddingHorizontal: 10, borderRadius: RADIUS.pill },
  titleTagText: { fontSize: 12, fontWeight: '800', color: COLORS.primary },
  levelTag: { alignSelf: 'flex-start', backgroundColor: COLORS.primary, paddingVertical: 2, paddingHorizontal: 9, borderRadius: RADIUS.pill },
  levelTagText: { fontSize: 13, fontWeight: '800', color: '#fff' },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: COLORS.ink },
  achievementCard: { flexDirection: 'row', backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 16, padding: 12, marginBottom: 10 },
  achievementTitle: { fontSize: 14.5, fontWeight: '700', color: COLORS.ink, flex: 1 },
  achievementDate: { fontSize: 11, color: COLORS.inkMuted48 },
  viewButton: { alignSelf: 'flex-start', height: 28, paddingHorizontal: 12, borderRadius: RADIUS.pill, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, alignItems: 'center', justifyContent: 'center' },
  viewButtonText: { fontSize: 11.5, fontWeight: '600', color: COLORS.ink },
  pagination: { flexDirection: 'row', justifyContent: 'center', gap: 6 },
  pageDot: { minWidth: 22, height: 22, borderRadius: 6, paddingHorizontal: 4, alignItems: 'center', justifyContent: 'center' },
  pageDotText: { fontSize: 12, color: COLORS.inkMuted48 },
  shortcutButton: { flex: 1, height: 46, borderRadius: 14, backgroundColor: '#E3F5E7', borderWidth: 1, borderColor: 'rgba(3,50,54,0.12)', alignItems: 'center', justifyContent: 'center' },
  shortcutButtonText: { fontSize: 14, fontWeight: '600', color: COLORS.primary },
  achOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 32 },
  achCard: { width: '100%', backgroundColor: COLORS.primary, borderRadius: 24, padding: 24, paddingTop: 28, alignItems: 'center', gap: 14 },
  achClose: { position: 'absolute', top: 14, right: 14 },
  achLabel: { fontSize: 10, fontWeight: '700', letterSpacing: 1, color: COLORS.mint, textTransform: 'uppercase' },
  achTitle: { fontSize: 20, fontWeight: '700', color: '#fff', textAlign: 'center' },
  achTime: { fontSize: 13, color: 'rgba(255,255,255,0.65)' },
  rewardBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: COLORS.goldTint, borderRadius: RADIUS.pill, paddingVertical: 8, paddingHorizontal: 14 },
  rewardBadgeLabel: { fontSize: 13, fontWeight: '700', color: COLORS.gold },
  rewardBadgeValue: { fontSize: 13, fontWeight: '700', color: COLORS.ink },
  achConfirmButton: { width: '100%', height: 48, borderRadius: RADIUS.pill, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center', marginTop: 6 },
  achConfirmText: { fontSize: 15, fontWeight: '700', color: COLORS.primary },
  glowOuter: { position: 'absolute', width: 88, height: 88, borderRadius: 9999, backgroundColor: 'rgba(139,209,157,0.35)' },
  glowInner: { position: 'absolute', width: 72, height: 72, borderRadius: 9999, backgroundColor: 'rgba(201,162,39,0.3)' },
  badgeCircle: { width: 56, height: 56, borderRadius: 9999, backgroundColor: COLORS.mint, alignItems: 'center', justifyContent: 'center' },
});
