import { StyleSheet } from 'react-native';
import { COLORS, RADIUS } from '../../../shared/디자인/tokens';


export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: COLORS.ink },
  content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 16, gap: 16 },
  card: { backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 18, padding: 16, gap: 12 },
  typeTag: { backgroundColor: '#FBEAE8', paddingVertical: 4, paddingHorizontal: 10, borderRadius: RADIUS.pill },
  typeTagText: { fontSize: 11, fontWeight: '700', color: '#B23A34' },
  statusChip: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: RADIUS.pill },
  statusChipText: { fontSize: 10.5, fontWeight: '700' },
  avatar: { width: 40, height: 40, borderRadius: 9999, backgroundColor: COLORS.mint, alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontSize: 15, fontWeight: '700', color: '#fff' },
  targetTitle: { fontSize: 15, fontWeight: '700', color: COLORS.ink },
  metaText: { fontSize: 12, color: COLORS.inkMuted48 },
  viewUserButton: { backgroundColor: '#E3F5E7', paddingVertical: 6, paddingHorizontal: 10, borderRadius: RADIUS.pill },
  viewUserButtonText: { fontSize: 12, fontWeight: '600', color: COLORS.primary },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: COLORS.ink },
  reasonBox: { backgroundColor: COLORS.parchment, borderRadius: 16, padding: 14, paddingHorizontal: 16 },
  reasonText: { fontSize: 13.5, color: COLORS.ink, lineHeight: 20 },
  evidenceBox: { flex: 1, aspectRatio: 1, backgroundColor: COLORS.parchment, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  evidenceText: { fontSize: 12, color: COLORS.inkMuted48, fontWeight: '600' },
  resolvedBox: { backgroundColor: COLORS.goldTint, borderRadius: 16, padding: 14, paddingHorizontal: 16 },
  resolvedText: { fontSize: 13.5, color: COLORS.ink, lineHeight: 20 },
  actionFooter: { paddingHorizontal: 20, paddingBottom: 22, paddingTop: 10, gap: 8, backgroundColor: 'rgba(255,255,255,0.7)', borderTopWidth: 1, borderTopColor: 'rgba(255,255,255,0.6)' },
  warnButton: { flex: 1, height: 46, borderRadius: RADIUS.pill, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, alignItems: 'center', justifyContent: 'center' },
  warnButtonText: { fontSize: 13.5, fontWeight: '700', color: COLORS.ink },
  suspendButton: { flex: 1, height: 46, borderRadius: RADIUS.pill, backgroundColor: '#B23A34', alignItems: 'center', justifyContent: 'center' },
  suspendButtonText: { fontSize: 13.5, fontWeight: '700', color: '#fff' },
  rejectButton: { height: 46, borderRadius: RADIUS.pill, borderWidth: 1, borderColor: COLORS.hairline, alignItems: 'center', justifyContent: 'center' },
  rejectButtonText: { fontSize: 13.5, fontWeight: '700', color: COLORS.inkMuted48 },
  toast: { position: 'absolute', left: '50%', bottom: 56, transform: [{ translateX: -100 }], backgroundColor: COLORS.ink, borderRadius: RADIUS.pill, paddingVertical: 12, paddingHorizontal: 20 },
  toastText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  confirmOverlay: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 32, backgroundColor: 'rgba(3,50,54,0.4)' },
  confirmCard: { width: '100%', maxWidth: 300, backgroundColor: '#fff', borderRadius: 22, padding: 22, gap: 14 },
  confirmTitle: { fontSize: 16.5, fontWeight: '700', color: COLORS.ink, flex: 1 },
  confirmDesc: { fontSize: 13, color: COLORS.inkMuted48, lineHeight: 19 },
  confirmCancel: { flex: 1, height: 46, borderRadius: RADIUS.pill, backgroundColor: COLORS.parchment, alignItems: 'center', justifyContent: 'center' },
  confirmCancelText: { fontSize: 14, fontWeight: '600', color: COLORS.ink },
  confirmOk: { flex: 1, height: 46, borderRadius: RADIUS.pill, alignItems: 'center', justifyContent: 'center' },
  confirmOkText: { fontSize: 14, fontWeight: '600', color: '#fff' },
});
