"""add updated_at to volunteer_center

Revision ID: 020f241889c6
Revises: 466da61361d7
Create Date: 2026-07-19 02:26:59.843979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '020f241889c6'
down_revision: Union[str, Sequence[str], None] = '466da61361d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_center', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='마지막 크롤링 확인 시각'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_center', 'updated_at')
    # ### end Alembic commands ###
