"""add quest_start table

Revision ID: 1b55d13dda56
Revises: 8a6992c46886
Create Date: 2026-08-03 14:04:01.599665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b55d13dda56'
down_revision: Union[str, Sequence[str], None] = '8a6992c46886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_start',
    sa.Column('start_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='시작한 사람'),
    sa.Column('quest_id', sa.BigInteger(), nullable=False, comment='시작된 퀘스트'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='시작한 일시'),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.quest_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('start_id'),
    sa.UniqueConstraint('user_id', 'quest_id', name='uq_quest_start_user_quest')
    )
    op.create_index(op.f('ix_quest_start_quest_id'), 'quest_start', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_start_user_id'), 'quest_start', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quest_start_user_id'), table_name='quest_start')
    op.drop_index(op.f('ix_quest_start_quest_id'), table_name='quest_start')
    op.drop_table('quest_start')
    # ### end Alembic commands ###
