"""add challenge columns

Revision ID: 24105004dbbf
Revises: ea54032b4702
Create Date: 2026-07-26 19:34:02.156213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24105004dbbf'
down_revision: Union[str, Sequence[str], None] = 'ea54032b4702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_submission', sa.Column('challenge_code', sa.String(length=10), nullable=True))
    op.add_column('quest_submission', sa.Column('challenge_media_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest_submission', 'challenge_media_url')
    op.drop_column('quest_submission', 'challenge_code')
    # ### end Alembic commands ###
