"""add condition_category, condition_count to badge

Revision ID: 26ac759a4d2c
Revises: 7969c67a4d67
Create Date: 2026-07-28 16:14:32.817895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26ac759a4d2c'
down_revision: Union[str, Sequence[str], None] = '7969c67a4d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('badge', sa.Column('condition_category', sa.String(length=30), nullable=False))
    op.add_column('badge', sa.Column('condition_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('badge', 'condition_count')
    op.drop_column('badge', 'condition_category')
    # ### end Alembic commands ###
