"""vertification db update

Revision ID: 2aaff4514f21
Revises: 0d1e4d626813
Create Date: 2026-07-22 12:29:45.161489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aaff4514f21'
down_revision: Union[str, Sequence[str], None] = '0d1e4d626813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_submission', sa.Column('extra_media_urls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest_submission', 'extra_media_urls')
    # ### end Alembic commands ###
