"""add unique constraint on user.nickname

Revision ID: 3c750708a755
Revises: 8a6992c46886
Create Date: 2026-08-03 17:12:51.450713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c750708a755'
down_revision: Union[str, Sequence[str], None] = '8a6992c46886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 【판단】 이미 중복 닉네임이 있는 DB 에서는 아래 create_unique_constraint 가
    # 실패한다. 그때 나오는 postgres 원문 에러는 "왜 실패했는지"는 알려줘도
    # "무엇을 고쳐야 하는지"는 알려주지 않는다. 먼저 세어보고, 중복이 있으면
    # 어떤 닉네임이 문제인지 짚어서 멈춘다.
    conn = op.get_bind()
    dups = conn.execute(sa.text(
        'SELECT nickname, count(*) FROM "user" GROUP BY nickname HAVING count(*) > 1'
    )).fetchall()

    if dups:
        detail = ", ".join(f"{row[0]}({row[1]}건)" for row in dups)
        raise RuntimeError(
            "닉네임이 중복된 사용자가 있어 unique 제약을 걸 수 없습니다: "
            f"{detail}\n"
            '한쪽 닉네임을 바꾼 뒤 다시 실행하세요. 예) '
            "UPDATE \"user\" SET nickname='새닉네임' WHERE user_id=<바꿀 유저>;"
        )

    op.create_unique_constraint('uq_user_nickname', 'user', ['nickname'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_nickname', 'user', type_='unique')
    # ### end Alembic commands ###
