"""add missing foreign keys for region, purchase, quest_submission, quest

Revision ID: 4416cb806eb1
Revises: 8595ff5e793f
Create Date: 2026-07-21 09:26:02.918368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4416cb806eb1'
down_revision: Union[str, Sequence[str], None] = '8595ff5e793f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('point_transaction', sa.Column('submission_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'point_transaction', 'quest_submission', ['submission_id'], ['submission_id'])
    op.create_foreign_key(None, 'point_transaction', 'purchase', ['purchase_id'], ['purchase_id'])
    op.create_foreign_key(None, 'quest_submission', 'quest', ['quest_id'], ['quest_id'])
    op.create_foreign_key(None, 'user', 'region', ['region_id'], ['region_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'quest_submission', type_='foreignkey')
    op.drop_constraint(None, 'point_transaction', type_='foreignkey')
    op.drop_constraint(None, 'point_transaction', type_='foreignkey')
    op.drop_column('point_transaction', 'submission_id')
    # ### end Alembic commands ###
