"""add error_message column to short_form

Revision ID: 466da61361d7
Revises: 9ed4f1e8f763
Create Date: 2026-07-18 16:17:40.227558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '466da61361d7'
down_revision: Union[str, Sequence[str], None] = '9ed4f1e8f763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_form', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_form', 'error_message')
    # ### end Alembic commands ###
