"""add Quest, Category table

Revision ID: 51abb4519a54
Revises: 0e4e08930cca
Create Date: 2026-07-14 21:43:46.524077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51abb4519a54'
down_revision: Union[str, Sequence[str], None] = '0e4e08930cca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='카테고리명 (예: 환경, 봉사)'),
    sa.Column('icon_url', sa.String(length=500), nullable=False, comment='카테고리 아이콘 이미지 URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='카테고리 활성화 상태'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('category', sa.JSON(), nullable=True),
    sa.Column('active_time', sa.String(length=50), nullable=True),
    sa.Column('preferred_difficulty', sa.Enum('VERY_EASY', 'EASY', 'NORMAL', 'HARD', 'VERY_HARD', name='difficulty'), nullable=True),
    sa.Column('profile_embedding', sa.JSON(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('point_balance', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), server_default='USER', nullable=False),
    sa.Column('current_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_provider')
    )
    op.create_table('quest',
    sa.Column('quest_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='카테고리 ID'),
    sa.Column('creator_id', sa.BigInteger(), nullable=False, comment='등록한 주체 ID (AI 또는 관리자/유저)'),
    sa.Column('quest_title', sa.String(length=200), nullable=False, comment='퀘스트 제목'),
    sa.Column('quest_description', sa.Text(), nullable=False, comment='퀘스트 상세 설명'),
    sa.Column('quest_target', sa.Enum('SOLO', 'TEAM', name='quest_target_enum'), nullable=False, comment='참여 방식 (SOLO / TEAM)'),
    sa.Column('quest_type', sa.Enum('VOLUNTEER', 'GOOD_DEED', name='quest_type_enum'), nullable=False, comment='퀘스트 종류 (VOLUNTEER / GOOD_DEED)'),
    sa.Column('quest_source', sa.Enum('USER', 'AI', 'ADMIN', name='quest_source_enum'), nullable=False, comment='등록 출처 (USER / AI / ADMIN)'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='봉사 장소 및 주소 (일상 퀘스트는 None)'),
    sa.Column('reward_point', sa.Integer(), nullable=True, comment='지급 보상 포인트'),
    sa.Column('reward_exp', sa.Integer(), nullable=True, comment='지급 보상 경험치'),
    sa.Column('difficulty', sa.Enum('VERY_EASY', 'EASY', 'NORMAL', 'HARD', 'VERY_HARD', name='quest_difficulty_enum'), nullable=False, comment='난이도 (VERY EASY ~ VERY HARD)'),
    sa.Column('quest_embedding', sa.JSON(), nullable=True, comment='벡터 검색용 퀘스트 임베딩 정보'),
    sa.Column('quest_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='quest_status_enum'), nullable=False, comment='진행 상태'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='퀘스트 수행 완료 일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quest_id')
    )
    op.drop_table('User')
    op.alter_column('ai_recommendation', 'recommendation_type',
               existing_type=sa.VARCHAR(length=20),
               comment='추천 타입 (VOLUNTEER / GOOD_DEED)',
               existing_comment='추천 타입 (VOLUNTEER / DAILY_GOOD_DEED)',
               existing_nullable=False)
    op.create_foreign_key(None, 'ai_recommendation', 'quest', ['quest_id'], ['quest_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ai_recommendation_log', 'user', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_recommendation_log', type_='foreignkey')
    op.drop_constraint(None, 'ai_recommendation', type_='foreignkey')
    op.alter_column('ai_recommendation', 'recommendation_type',
               existing_type=sa.VARCHAR(length=20),
               comment='추천 타입 (VOLUNTEER / DAILY_GOOD_DEED)',
               existing_comment='추천 타입 (VOLUNTEER / GOOD_DEED)',
               existing_nullable=False)
    op.create_table('User',
    sa.Column('user_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('provider_user_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('category', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('active_time', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('preferred_difficulty', postgresql.ENUM('VERY_EASY', 'EASY', 'NORMAL', 'HARD', 'VERY_HARD', name='difficulty'), autoincrement=False, nullable=True),
    sa.Column('profile_embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('profile_image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('trust_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point_balance', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_xp', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('current_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('daily_streak', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'USER', name='userrole'), server_default=sa.text("'USER'::userrole"), autoincrement=False, nullable=False),
    sa.Column('current_latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('current_longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('User_pkey')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('provider', 'provider_user_id', name=op.f('uq_user_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('quest')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
