"""i very hate fucking quest

Revision ID: 5891ef139e70
Revises: 2fc927449bab
Create Date: 2026-07-30 15:18:34.061300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5891ef139e70'
down_revision: Union[str, Sequence[str], None] = '2fc927449bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quest_hidden_preference',
    sa.Column('hidden_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='치운 사람'),
    sa.Column('quest_id', sa.BigInteger(), nullable=False, comment='치워진 퀘스트'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='치운 일시'),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.quest_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hidden_id'),
    sa.UniqueConstraint('user_id', 'quest_id', name='uq_quest_hidden_preference_user_quest')
    )
    op.create_index(op.f('ix_quest_hidden_preference_quest_id'), 'quest_hidden_preference', ['quest_id'], unique=False)
    op.create_index(op.f('ix_quest_hidden_preference_user_id'), 'quest_hidden_preference', ['user_id'], unique=False)
    op.add_column('quest', sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='시용자가 삭제처리한 퀘스트'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest', 'is_deleted')
    op.drop_index(op.f('ix_quest_hidden_preference_user_id'), table_name='quest_hidden_preference')
    op.drop_index(op.f('ix_quest_hidden_preference_quest_id'), table_name='quest_hidden_preference')
    op.drop_table('quest_hidden_preference')
    # ### end Alembic commands ###
