"""add vol_title to volunteer_center

Revision ID: 5c566533b8f1
Revises: 2aaff4514f21
Create Date: 2026-07-25 13:33:29.218416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c566533b8f1'
down_revision: Union[str, Sequence[str], None] = '2aaff4514f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_center', sa.Column('vol_title', sa.String(length=500), nullable=True, comment='봉사 모집 제목'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_center', 'vol_title')
    # ### end Alembic commands ###
