"""add_ai_category_to_volunteer_center

Revision ID: 6b233f24a890
Revises: 5c566533b8f1
Create Date: 2026-07-26 21:50:23.213540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b233f24a890'
down_revision: Union[str, Sequence[str], None] = '5c566533b8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer_center', sa.Column('ai_category', sa.String(length=50), nullable=True, comment='AI 임베딩 기반 의미 카테고리 (환경/동물/아동청소년/어르신/장애인/교육/다문화/재난안전/기타)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_center', 'ai_category')
    # ### end Alembic commands ###
