"""update volunteer_center DB i am jungyoon

Revision ID: 70aadfa6efeb
Revises: 5891ef139e70
Create Date: 2026-07-30 15:58:26.221549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70aadfa6efeb'
down_revision: Union[str, Sequence[str], None] = '5891ef139e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'purchase', 'item', ['item_id'], ['item_id'], ondelete='RESTRICT')
    op.add_column('volunteer_center', sa.Column('embedding', sa.JSON(), nullable=True, comment='봉사 공고 텍스트 임베딩 벡터'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_center', 'embedding')
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    # ### end Alembic commands ###
