"""Add ai recommendation tables

Revision ID: 72dd988b3ae2
Revises: d67b0982848d
Create Date: 2026-07-13 22:42:02.859244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dd988b3ae2'
down_revision: Union[str, Sequence[str], None] = 'd67b0982848d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_recommendation_log',
    sa.Column('ai_log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.Column('request_context', sa.JSON(), nullable=False, comment='추천 요청 당시 수집된 Context JSON'),
    sa.Column('response_context', sa.JSON(), nullable=True, comment='AI가 반환한 최종 추천 결과 데이터 JSON'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='로그 생성 일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='로그 수정 일시'),
    sa.PrimaryKeyConstraint('ai_log_id')
    )
    op.create_table('ai_recommendation',
    sa.Column('ai_rec_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ai_log_id', sa.BigInteger(), nullable=False, comment='추천 로그 ID'),
    sa.Column('quest_id', sa.BigInteger(), nullable=True, comment='Quest DB 연동 ID'),
    sa.Column('score', sa.Float(), nullable=True, comment='추천 유사도 점수'),
    sa.Column('reason', sa.Text(), nullable=True, comment='AI 추천 사유'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='추천 순위'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.ForeignKeyConstraint(['ai_log_id'], ['ai_recommendation_log.ai_log_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_rec_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_recommendation')
    op.drop_table('ai_recommendation_log')
    # ### end Alembic commands ###
