"""add quest summary cache to volunteer_center and center fk to quest

Revision ID: 815da3e7c6aa
Revises: d9e371890710
Create Date: 2026-08-02 14:02:29.325020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '815da3e7c6aa'
down_revision: Union[str, Sequence[str], None] = 'd9e371890710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gooddeedquest_public_volunteer_center')
    op.add_column('quest', sa.Column('volunteer_center_id', sa.BigInteger(), nullable=True, comment='원본 봉사 공고 ID (VOLUNTEER 전용, GOOD_DEED는 None)'))
    op.create_foreign_key(None, 'quest', 'volunteer_center', ['volunteer_center_id'], ['center_id'], ondelete='SET NULL')
    op.add_column('volunteer_center', sa.Column('quest_title', sa.String(length=200), nullable=True, comment='AI가 생성한 퀘스트용 정리 제목 (장식문자·모집·차수 제거, Quest.quest_title과 동일 길이)'))
    op.add_column('volunteer_center', sa.Column('quest_summary', sa.Text(), nullable=True, comment='AI가 생성한 한 문장 활동 요약 (퀘스트 상세 화면 설명문)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer_center', 'quest_summary')
    op.drop_column('volunteer_center', 'quest_title')
    op.drop_constraint(None, 'quest', type_='foreignkey')
    op.drop_column('quest', 'volunteer_center_id')
    op.create_table('gooddeedquest_public_volunteer_center',
    sa.Column('center_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('region_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('vol_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('vol_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('target', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('vms_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('vol_qual', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('vol_act', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('vol_date', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=10, scale=7), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('vol_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ai_category', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
