"""add AI recommendation title, description, type

Revision ID: 844c3cbe4c9e
Revises: ced371da50ea
Create Date: 2026-07-14 14:04:18.616462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '844c3cbe4c9e'
down_revision: Union[str, Sequence[str], None] = 'ced371da50ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_recommendation', sa.Column('title', sa.String(length=200), nullable=False, comment='추천 당시의 퀘스트 제목'))
    op.add_column('ai_recommendation', sa.Column('description', sa.Text(), nullable=False, comment='추천 당시의 퀘스트 상세 설명'))
    op.add_column('ai_recommendation', sa.Column('recommendation_type', sa.String(length=20), nullable=False, comment='추천 타입 (VOLUNTEER / DAILY_GOOD_DEED)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_recommendation', 'recommendation_type')
    op.drop_column('ai_recommendation', 'description')
    op.drop_column('ai_recommendation', 'title')
    # ### end Alembic commands ###
