"""Who are you?

Revision ID: 8a6992c46886
Revises: 05eb01e7b2b2
Create Date: 2026-08-03 01:40:11.266880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6992c46886'
down_revision: Union[str, Sequence[str], None] = '05eb01e7b2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('token_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='이 토큰의 주인'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='토큰 원문의 SHA-256'),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='만료 시각'),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='회수된 시각. 값이 있으면 못 씀'),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
