"""make bgm_id, title, mood_tag not null

Revision ID: 91735051701b
Revises: 97d8271df797
Create Date: 2026-07-14 11:11:16.342007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91735051701b'
down_revision: Union[str, Sequence[str], None] = '97d8271df797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('background_music', 'mood_tag',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('shortform', 'bgm_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shortform', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shortform', 'title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('shortform', 'bgm_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('background_music', 'mood_tag',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
