"""feat: shortform, background_music 테이블 모델 추가

Revision ID: 97d8271df797
Revises: d67b0982848d
Create Date: 2026-07-14 09:32:06.796739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97d8271df797'
down_revision: Union[str, Sequence[str], None] = 'd67b0982848d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_music',
    sa.Column('bgm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('mood_tag', sa.String(length=50), nullable=True),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('source_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bgm_id')
    )
    op.create_index(op.f('ix_background_music_mood_tag'), 'background_music', ['mood_tag'], unique=False)
    op.create_table('shortform',
    sa.Column('shorts_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bgm_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('ai_generated_captions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_video_s3_key', sa.String(length=512), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='shortform_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bgm_id'], ['background_music.bgm_id'], ),
    sa.PrimaryKeyConstraint('shorts_id')
    )
    op.create_index(op.f('ix_shortform_bgm_id'), 'shortform', ['bgm_id'], unique=False)
    op.create_index(op.f('ix_shortform_user_id'), 'shortform', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortform_user_id'), table_name='shortform')
    op.drop_index(op.f('ix_shortform_bgm_id'), table_name='shortform')
    op.drop_table('shortform')
    op.drop_index(op.f('ix_background_music_mood_tag'), table_name='background_music')
    op.drop_table('background_music')
    # ### end Alembic commands ###
