"""region_id nullable_frue_ifx

Revision ID: 9ed4f1e8f763
Revises: cd049301050f
Create Date: 2026-07-17 20:01:17.663959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ed4f1e8f763'
down_revision: Union[str, Sequence[str], None] = 'cd049301050f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortform_bgm_id'), table_name='short_form')
    op.drop_index(op.f('ix_shortform_user_id'), table_name='short_form')
    op.create_index(op.f('ix_short_form_bgm_id'), 'short_form', ['bgm_id'], unique=False)
    op.alter_column('user', 'region_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'region_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_index(op.f('ix_short_form_bgm_id'), table_name='short_form')
    op.create_index(op.f('ix_shortform_user_id'), 'short_form', ['user_id'], unique=False)
    op.create_index(op.f('ix_shortform_bgm_id'), 'short_form', ['bgm_id'], unique=False)
    # ### end Alembic commands ###
