"""add user table v2

Revision ID: aa1368a37820
Revises: 2f771c4131a3
Create Date: 2026-07-14 16:38:58.274991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa1368a37820'
down_revision: Union[str, Sequence[str], None] = '2f771c4131a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('category', sa.JSON(), nullable=True),
    sa.Column('active_time', sa.String(length=50), nullable=True),
    sa.Column('preferred_difficulty', sa.Enum('VERY_EASY', 'EASY', 'NORMAL', 'HARD', 'VERY_HARD', name='difficulty'), nullable=True),
    sa.Column('profile_embedding', sa.JSON(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('point_balance', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), server_default='USER', nullable=False),
    sa.Column('current_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
