"""admin models change.

Revision ID: bc95f2a0c3b6
Revises: f828ee80f9bb
Create Date: 2026-07-16 15:03:59.455826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc95f2a0c3b6'
down_revision: Union[str, Sequence[str], None] = 'f828ee80f9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report', 'post_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(op.f('report_post_id_fkey'), 'report', type_='foreignkey')
    op.create_foreign_key(None, 'report', 'community_post', ['post_id'], ['post_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.create_foreign_key(op.f('report_post_id_fkey'), 'report', 'community_post', ['post_id'], ['post_id'], ondelete='CASCADE')
    op.alter_column('report', 'post_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###
