"""active_time column type to json

Revision ID: c54f214612ce
Revises: a3c090ff77c2
Create Date: 2026-07-20 16:45:34.413298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c54f214612ce'
down_revision: Union[str, Sequence[str], None] = 'a3c090ff77c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 값이 VARCHAR로 저장된 "{MORNING}" 같은 문자열이라 JSON으로 직접 캐스팅이 안 됨.
    # 개발 단계 데이터라 비우고 타입만 바꿈 (운영 데이터가 있었다면 별도 변환 스크립트 필요).
    op.execute('UPDATE "user" SET active_time = NULL')
    op.alter_column('user', 'active_time',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using='active_time::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active_time',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
