"""update Quest DB

Revision ID: d41d72d90594
Revises: 75873e83ed5d
Create Date: 2026-07-21 12:47:49.254615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41d72d90594'
down_revision: Union[str, Sequence[str], None] = '75873e83ed5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest', sa.Column('estimated_duration', sa.Integer(), nullable=True, comment='예상 소요 시간 (분 단위)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quest', 'estimated_duration')
    # ### end Alembic commands ###
