"""add category code column

Revision ID: ea54032b4702
Revises: 2aaff4514f21
Create Date: 2026-07-26 13:50:17.251045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea54032b4702'
down_revision: Union[str, Sequence[str], None] = '5c566533b8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 기존 한글 카테고리명 → 프론트 아이콘 코드 (theme.ts의 CATEGORY_DEFS와 일치해야 함)
NAME_TO_CODE = {
    "봉사": "volunteer",
    "환경": "environment",
    "나눔": "sharing",
    "동물": "animal",
    "지역사회": "community",
    "기타": "other",
}


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('category', sa.Column('code', sa.String(length=30), server_default='other', nullable=False, comment='프론트 아이콘 매칭용 코드 (environment, volunteer 등)'))

    # 이미 있는 카테고리 행들의 code를 한글명 기준으로 채운다 (매칭 안 되면 other 유지)
    for name, code in NAME_TO_CODE.items():
        op.execute(
            sa.text("UPDATE category SET code = :code WHERE name = :name").bindparams(code=code, name=name)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'code')
    # ### end Alembic commands ###
