"""initial_migration

Revision ID: f828ee80f9bb
Revises: 
Create Date: 2026-07-16 12:31:54.427141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f828ee80f9bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_music',
    sa.Column('bgm_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('mood_tag', sa.String(length=50), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('source_info', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('bgm_id')
    )
    op.create_index(op.f('ix_background_music_mood_tag'), 'background_music', ['mood_tag'], unique=False)
    op.create_table('badge',
    sa.Column('badge_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=False),
    sa.Column('badge_category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False, comment='카테고리명 (예: 환경, 봉사)'),
    sa.Column('icon_url', sa.String(length=500), nullable=False, comment='카테고리 아이콘 이미지 URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='카테고리 활성화 상태'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('city',
    sa.Column('city_id', sa.BigInteger(), nullable=False, comment='행정구역 고유번호'),
    sa.Column('city_name', sa.String(length=100), nullable=False, comment='행정구역명'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_index(op.f('ix_city_city_id'), 'city', ['city_id'], unique=False)
    op.create_table('competition',
    sa.Column('competition_id', sa.BigInteger(), nullable=False, comment='대회 고유번호'),
    sa.Column('title', sa.String(length=200), nullable=True, comment='대회명'),
    sa.Column('description', sa.Text(), nullable=True, comment='대회 설명'),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SETTLING', name='competitionstatus'), nullable=True, comment='대회 상태 (IN_PROGRESS/SETTLING)'),
    sa.Column('start_at', sa.TIMESTAMP(), nullable=True, comment='시작일시'),
    sa.Column('end_at', sa.TIMESTAMP(), nullable=True, comment='종료일시'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.PrimaryKeyConstraint('competition_id')
    )
    op.create_table('item',
    sa.Column('item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('is_equipped', sa.Boolean(), nullable=False, comment='장착 상태 여부'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='상품 이름'),
    sa.Column('description', sa.Text(), nullable=False, comment='상품 상세 설명'),
    sa.Column('price_point', sa.Integer(), nullable=False, comment='상품 가격 (포인트 단위)'),
    sa.Column('image_url', sa.String(length=500), nullable=False, comment='상품 이미지 URL'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='상점 노출 여부'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='등록 일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('region_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('category', sa.JSON(), nullable=True),
    sa.Column('active_time', sa.String(length=50), nullable=True),
    sa.Column('preferred_difficulty', sa.Enum('VERY_EASY', 'EASY', 'NORMAL', 'HARD', 'VERY_HARD', name='difficulty'), nullable=True),
    sa.Column('profile_embedding', sa.JSON(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=255), nullable=True),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('point_balance', sa.Integer(), nullable=False),
    sa.Column('current_xp', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('daily_streak', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), server_default='USER', nullable=False),
    sa.Column('current_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('current_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_provider')
    )
    op.create_table('ai_recommendation_log',
    sa.Column('ai_log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='사용자 ID'),
    sa.Column('request_context', sa.JSON(), nullable=False, comment='추천 요청 당시 수집된 Context JSON'),
    sa.Column('response_context', sa.JSON(), nullable=True, comment='AI가 반환한 최종 추천 결과 데이터 JSON'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='로그 생성 일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='로그 수정 일시'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ai_log_id')
    )
    op.create_table('point_transaction',
    sa.Column('transaction_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('purchase_id', sa.BigInteger(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('EARN', 'SPEND', name='transactiontype'), nullable=True),
    sa.Column('balance_after', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_table('purchase',
    sa.Column('purchase_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='구매한 유저 ID'),
    sa.Column('item_id', sa.BigInteger(), nullable=False, comment='구매한 상품 ID'),
    sa.Column('status', sa.Enum('COMPLETED', 'REFUNDED', name='purchase_status_enum'), nullable=False, comment='구매 진행 상태 (COMPLETED / REFUNDED)'),
    sa.Column('purchased_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='구매 일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.ForeignKeyConstraint(['item_id'], ['item.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('purchase_id')
    )
    op.create_table('quest',
    sa.Column('quest_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False, comment='카테고리 ID'),
    sa.Column('creator_id', sa.BigInteger(), nullable=False, comment='등록한 주체 ID (AI 또는 관리자/유저)'),
    sa.Column('quest_title', sa.String(length=200), nullable=False, comment='퀘스트 제목'),
    sa.Column('quest_description', sa.Text(), nullable=False, comment='퀘스트 상세 설명'),
    sa.Column('quest_target', sa.Enum('SOLO', 'TEAM', name='quest_target_enum'), nullable=False, comment='참여 방식 (SOLO / TEAM)'),
    sa.Column('quest_type', sa.Enum('VOLUNTEER', 'GOOD_DEED', name='quest_type_enum'), nullable=False, comment='퀘스트 종류 (VOLUNTEER / GOOD_DEED)'),
    sa.Column('quest_source', sa.Enum('USER', 'AI', 'ADMIN', name='quest_source_enum'), nullable=False, comment='등록 출처 (USER / AI / ADMIN)'),
    sa.Column('location', sa.String(length=255), nullable=True, comment='봉사 장소 및 주소 (일상 퀘스트는 None)'),
    sa.Column('reward_point', sa.Integer(), nullable=True, comment='지급 보상 포인트'),
    sa.Column('reward_exp', sa.Integer(), nullable=True, comment='지급 보상 경험치'),
    sa.Column('difficulty', sa.Enum('VERY_EASY', 'EASY', 'NORMAL', 'HARD', 'VERY_HARD', name='quest_difficulty_enum'), nullable=False, comment='난이도 (VERY EASY ~ VERY HARD)'),
    sa.Column('quest_embedding', sa.JSON(), nullable=True, comment='벡터 검색용 퀘스트 임베딩 정보'),
    sa.Column('quest_status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='quest_status_enum'), nullable=False, comment='진행 상태'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True, comment='퀘스트 수행 완료 일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['creator_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('quest_id')
    )
    op.create_table('quest_submission',
    sa.Column('submission_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('quest_explain', sa.String(length=1000), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=True),
    sa.Column('media_type', sa.Enum('PHOTO', 'VIDEO', name='mediatype'), nullable=True),
    sa.Column('media_hash', sa.String(length=255), nullable=True),
    sa.Column('media_embedding', sa.JSON(), nullable=True),
    sa.Column('ai_verdict', sa.JSON(), nullable=True),
    sa.Column('ai_generated_suspicion', sa.Boolean(), nullable=True),
    sa.Column('final_status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='submissionstatus'), server_default='PENDING', nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('submission_id')
    )
    op.create_table('region',
    sa.Column('region_id', sa.BigInteger(), nullable=False, comment='지역 고유 번호'),
    sa.Column('city_id', sa.BigInteger(), nullable=False, comment='시도FK'),
    sa.Column('region_name', sa.String(length=100), nullable=False, comment='지역명(시군구)'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.PrimaryKeyConstraint('region_id')
    )
    op.create_index(op.f('ix_region_region_id'), 'region', ['region_id'], unique=False)
    op.create_table('shortform',
    sa.Column('shorts_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('bgm_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('ai_generated_captions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_video_s3_key', sa.String(length=512), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='shortform_status_enum'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bgm_id'], ['background_music.bgm_id'], ),
    sa.PrimaryKeyConstraint('shorts_id')
    )
    op.create_index(op.f('ix_shortform_bgm_id'), 'shortform', ['bgm_id'], unique=False)
    op.create_index(op.f('ix_shortform_user_id'), 'shortform', ['user_id'], unique=False)
    op.create_table('user_activity_log',
    sa.Column('activity_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('access_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('activity_id'),
    sa.UniqueConstraint('user_id', 'access_date', name='uq_user_activity_log_user_date')
    )
    op.create_index(op.f('ix_user_activity_log_access_date'), 'user_activity_log', ['access_date'], unique=False)
    op.create_index(op.f('ix_user_activity_log_user_id'), 'user_activity_log', ['user_id'], unique=False)
    op.create_table('user_badge',
    sa.Column('user_badge_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('badge_id', sa.BigInteger(), nullable=False),
    sa.Column('is_equipped', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('awarded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.badge_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_badge_id')
    )
    op.create_table('ai_recommendation',
    sa.Column('ai_rec_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ai_log_id', sa.BigInteger(), nullable=False, comment='추천 로그 ID'),
    sa.Column('quest_id', sa.BigInteger(), nullable=True, comment='Quest DB 연동 ID'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='추천 당시의 퀘스트 제목'),
    sa.Column('description', sa.Text(), nullable=False, comment='추천 당시의 퀘스트 상세 설명'),
    sa.Column('recommendation_type', sa.String(length=20), nullable=False, comment='추천 타입 (VOLUNTEER / GOOD_DEED)'),
    sa.Column('score', sa.Float(), nullable=True, comment='추천 유사도 점수'),
    sa.Column('reason', sa.Text(), nullable=True, comment='AI 추천 사유'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='추천 순위'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정 일시'),
    sa.ForeignKeyConstraint(['ai_log_id'], ['ai_recommendation_log.ai_log_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.quest_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ai_rec_id')
    )
    op.create_table('community_post',
    sa.Column('post_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('submission_id', sa.BigInteger(), nullable=True),
    sa.Column('media_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['quest_submission.submission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_index(op.f('ix_community_post_submission_id'), 'community_post', ['submission_id'], unique=False)
    op.create_index(op.f('ix_community_post_user_id'), 'community_post', ['user_id'], unique=False)
    op.create_table('competition_contribution',
    sa.Column('contribution_id', sa.BigInteger(), nullable=False, comment='기여 고유번호'),
    sa.Column('competition_id', sa.BigInteger(), nullable=False, comment='대회 FK'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='기여자 user FK'),
    sa.Column('submission_id', sa.BigInteger(), nullable=False, comment='퀘스트 인증 제출 FK'),
    sa.Column('region_id', sa.BigInteger(), nullable=False, comment='기여 지역 FK'),
    sa.Column('points', sa.Integer(), nullable=True, comment='획득 포인트'),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True, comment='수정일시'),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.competition_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['quest_submission.submission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('contribution_id')
    )
    op.create_index(op.f('ix_competition_contribution_region_id'), 'competition_contribution', ['region_id'], unique=False)
    op.create_table('competition_participant',
    sa.Column('participant_id', sa.BigInteger(), nullable=False, comment='참가 고유번호'),
    sa.Column('competition_id', sa.BigInteger(), nullable=False, comment='대회 FK'),
    sa.Column('region_id', sa.BigInteger(), nullable=False, comment='참가 지역 FK'),
    sa.Column('score', sa.Integer(), nullable=True, comment='지역 누적 점수'),
    sa.Column('rank', sa.Integer(), nullable=True, comment='지역 순위'),
    sa.Column('joined_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='참가일시'),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.competition_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    op.create_index(op.f('ix_competition_participant_region_id'), 'competition_participant', ['region_id'], unique=False)
    op.create_table('team',
    sa.Column('team_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('leader_id', sa.BigInteger(), nullable=False),
    sa.Column('quest_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('notification', sa.Text(), server_default='잘 부탁드립니다.', nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_members', sa.Integer(), server_default='4', nullable=False),
    sa.Column('status', sa.Enum('RECRUITING', 'ACTIVE', 'EXPIRED', 'DISBANDED', name='team_status'), server_default='RECRUITING', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_members BETWEEN 2 AND 10', name='ck_max_members'),
    sa.ForeignKeyConstraint(['leader_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['quest.quest_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('volunteer_center',
    sa.Column('center_id', sa.BigInteger(), nullable=False, comment='봉사센터 ID'),
    sa.Column('region_id', sa.BigInteger(), nullable=False, comment='지역 FK'),
    sa.Column('vol_name', sa.String(length=200), nullable=True, comment='봉사센터명'),
    sa.Column('vol_address', sa.String(length=255), nullable=True, comment='봉사센터 주소'),
    sa.Column('target', sa.String(length=200), nullable=True, comment='봉사 대상'),
    sa.Column('vms_url', sa.String(length=500), nullable=True, comment='VMS 원본 URL'),
    sa.Column('vol_qual', sa.String(length=500), nullable=True, comment='봉사 자격요건'),
    sa.Column('vol_act', sa.String(length=2000), nullable=True, comment='봉사 활동내용'),
    sa.Column('vol_date', sa.String(length=1000), nullable=True, comment='봉사 가능일자'),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='봉사센터 위도'),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True, comment='봉사센터 경도'),
    sa.ForeignKeyConstraint(['region_id'], ['region.region_id'], ),
    sa.PrimaryKeyConstraint('center_id')
    )
    op.create_index(op.f('ix_volunteer_center_center_id'), 'volunteer_center', ['center_id'], unique=False)
    op.create_table('comment',
    sa.Column('comment_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_post.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comment_post_id'), 'comment', ['post_id'], unique=False)
    op.create_index(op.f('ix_comment_user_id'), 'comment', ['user_id'], unique=False)
    op.create_table('feed_hidden_preference',
    sa.Column('hidden_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_post.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hidden_id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_feed_hidden_preference_user_post')
    )
    op.create_index(op.f('ix_feed_hidden_preference_post_id'), 'feed_hidden_preference', ['post_id'], unique=False)
    op.create_index(op.f('ix_feed_hidden_preference_user_id'), 'feed_hidden_preference', ['user_id'], unique=False)
    op.create_table('post_like',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_post.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_table('report',
    sa.Column('report_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('reporter_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='report_status'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_post.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('report_id'),
    sa.UniqueConstraint('reporter_id', 'post_id', name='uq_report_reporter_post')
    )
    op.create_index(op.f('ix_report_post_id'), 'report', ['post_id'], unique=False)
    op.create_index(op.f('ix_report_reporter_id'), 'report', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_report_reviewed_by'), 'report', ['reviewed_by'], unique=False)
    op.create_table('team_invite',
    sa.Column('invite_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='team_invite_status'), server_default='PENDING', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('invite_id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_invite_team_user')
    )
    op.create_table('team_member',
    sa.Column('team_member_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_in_team', sa.Enum('LEADER', 'MEMBER', name='team_member_role'), server_default='MEMBER', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('team_member_id'),
    sa.UniqueConstraint('team_id', 'user_id', name='uq_team_member_team_user')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_member')
    op.drop_table('team_invite')
    op.drop_index(op.f('ix_report_reviewed_by'), table_name='report')
    op.drop_index(op.f('ix_report_reporter_id'), table_name='report')
    op.drop_index(op.f('ix_report_post_id'), table_name='report')
    op.drop_table('report')
    op.drop_table('post_like')
    op.drop_index(op.f('ix_feed_hidden_preference_user_id'), table_name='feed_hidden_preference')
    op.drop_index(op.f('ix_feed_hidden_preference_post_id'), table_name='feed_hidden_preference')
    op.drop_table('feed_hidden_preference')
    op.drop_index(op.f('ix_comment_user_id'), table_name='comment')
    op.drop_index(op.f('ix_comment_post_id'), table_name='comment')
    op.drop_table('comment')
    op.drop_index(op.f('ix_volunteer_center_center_id'), table_name='volunteer_center')
    op.drop_table('volunteer_center')
    op.drop_table('team')
    op.drop_index(op.f('ix_competition_participant_region_id'), table_name='competition_participant')
    op.drop_table('competition_participant')
    op.drop_index(op.f('ix_competition_contribution_region_id'), table_name='competition_contribution')
    op.drop_table('competition_contribution')
    op.drop_index(op.f('ix_community_post_user_id'), table_name='community_post')
    op.drop_index(op.f('ix_community_post_submission_id'), table_name='community_post')
    op.drop_table('community_post')
    op.drop_table('ai_recommendation')
    op.drop_table('user_badge')
    op.drop_index(op.f('ix_user_activity_log_user_id'), table_name='user_activity_log')
    op.drop_index(op.f('ix_user_activity_log_access_date'), table_name='user_activity_log')
    op.drop_table('user_activity_log')
    op.drop_index(op.f('ix_shortform_user_id'), table_name='shortform')
    op.drop_index(op.f('ix_shortform_bgm_id'), table_name='shortform')
    op.drop_table('shortform')
    op.drop_index(op.f('ix_region_region_id'), table_name='region')
    op.drop_table('region')
    op.drop_table('quest_submission')
    op.drop_table('quest')
    op.drop_table('purchase')
    op.drop_table('point_transaction')
    op.drop_table('ai_recommendation_log')
    op.drop_table('user')
    op.drop_table('item')
    op.drop_table('competition')
    op.drop_index(op.f('ix_city_city_id'), table_name='city')
    op.drop_table('city')
    op.drop_table('category')
    op.drop_table('badge')
    op.drop_index(op.f('ix_background_music_mood_tag'), table_name='background_music')
    op.drop_table('background_music')
    # ### end Alembic commands ###
