import { StyleSheet } from 'react-native';

export const COLORS = {
  primary: '#033236',
  canvas: '#FFFFFF',
  parchment: '#F6F6F6',
  ink: '#1D1D1F',
  inkMuted48: '#7A7A7A',
  hairline: 'rgba(0,0,0,0.08)',
  hairlineSolid: 'rgba(0,0,0,0.18)',
  gold: '#C9A227',
  goldTint: '#FDF6E3',
  mint: '#8BD19D',
};
export const RADIUS = { lg: 18, xl: 24, pill: 9999 };

export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 10 },
  logoBadge: { width: 30, height: 30, borderRadius: 9, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  content: { flex: 1, paddingHorizontal: 24, paddingTop: 44, gap: 20 },
  badgeCircle: { width: 60, height: 60, marginBottom: -30, zIndex: 2 },
  badgeCircleGradient: { width: 60, height: 60, borderRadius: 9999, alignItems: 'center', justifyContent: 'center' },
  questCardBorder: { width: '100%', borderRadius: 26, padding: 2 },
  questCard: { borderRadius: 24, paddingVertical: 56, paddingHorizontal: 24, minHeight: 260, alignItems: 'center', justifyContent: 'center', gap: 16, overflow: 'hidden' },
  questTitle: { fontSize: 22, fontWeight: '700', color: COLORS.goldTint, textAlign: 'center', letterSpacing: -0.3 },
  rewardRow: { flexDirection: 'row', gap: 8 },
  rewardBadge: { flexDirection: 'row', alignItems: 'center', gap: 5, backgroundColor: COLORS.goldTint, borderRadius: RADIUS.pill, paddingVertical: 8, paddingHorizontal: 14 },
  rewardBadgeLabel: { fontSize: 13, fontWeight: '700', color: COLORS.gold },
  rewardBadgeValue: { fontSize: 13, fontWeight: '700', color: COLORS.ink },
  sectionLabel: { fontSize: 13, fontWeight: '500', color: COLORS.inkMuted48 },
  description: { fontSize: 15, color: COLORS.ink, lineHeight: 22 },
  startButton: { height: 50, borderRadius: RADIUS.pill, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  startButtonText: { fontSize: 17, letterSpacing: -0.37, color: COLORS.canvas, fontWeight: '600' },
  sheetOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(3,50,54,0.45)' },
  sheet: { backgroundColor: COLORS.canvas, borderTopLeftRadius: 26, borderTopRightRadius: 26, paddingHorizontal: 24, paddingTop: 14, paddingBottom: 28, maxHeight: '86%' },
  sheetHandle: { width: 36, height: 4, borderRadius: 9999, backgroundColor: 'rgba(0,0,0,0.14)', alignSelf: 'center', marginBottom: 14 },
  sheetHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sheetTitle: { fontSize: 19, fontWeight: '700', color: COLORS.ink, letterSpacing: -0.3, flex: 1 },
  questSummaryRow: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: COLORS.parchment, borderRadius: 14, padding: 14, marginTop: 16 },
  questSummaryIcon: { width: 36, height: 36, borderRadius: 10, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  questSummaryTitle: { fontSize: 14, fontWeight: '600', color: COLORS.ink },
  questSummaryReward: { fontSize: 12, color: COLORS.inkMuted48, marginTop: 2 },
  uploadBox: { height: 160, borderRadius: 20, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  uploadCheckBadge: { width: 44, height: 44, borderRadius: 9999, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  uploadTitle: { fontSize: 14, fontWeight: '600', color: COLORS.ink },
  uploadHint: { fontSize: 12, color: COLORS.inkMuted48 },
  input: { height: 48, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 14, paddingHorizontal: 16, fontSize: 15, color: COLORS.ink },
  textarea: { height: 70, paddingVertical: 12, textAlignVertical: 'top' },
  noticeCard: { backgroundColor: COLORS.goldTint, borderRadius: 14, paddingVertical: 12, paddingHorizontal: 16, alignItems: 'center' },
  noticeText: { fontSize: 13, color: COLORS.gold, fontWeight: '600', textAlign: 'center' },
  submitButton: { height: 50, borderRadius: RADIUS.pill, alignItems: 'center', justifyContent: 'center' },
  submitButtonText: { fontSize: 17, letterSpacing: -0.37, fontWeight: '600' },
  approvedCheckCircle: { width: 76, height: 76, borderRadius: 9999, alignItems: 'center', justifyContent: 'center' },
  approvedTitle: { fontSize: 20, fontWeight: '700', color: COLORS.ink, letterSpacing: -0.3 },
  approvedSubtitle: { fontSize: 13, color: COLORS.inkMuted48 },
});
