import { StyleSheet } from 'react-native';
import { COLORS, RADIUS } from '../../../shared/디자인/tokens';


export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerTitle: { fontSize: 18, fontWeight: '700', color: COLORS.ink },
  content: { paddingHorizontal: 20, paddingTop: 14, paddingBottom: 22, gap: 14 },
  searchBar: { height: 48, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 14, flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 14 },
  searchInput: { flex: 1, fontSize: 15, color: COLORS.ink },
  filterChip: { height: 32, paddingHorizontal: 14, borderRadius: 14, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, alignItems: 'center', justifyContent: 'center' },
  filterChipActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  filterChipText: { fontSize: 13, fontWeight: '600', color: COLORS.ink },
  countText: { fontSize: 12.5, fontWeight: '600', color: COLORS.inkMuted48 },
  listCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 16, overflow: 'hidden' },
  userRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 12, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.05)' },
  avatar: { width: 36, height: 36, borderRadius: 9999, backgroundColor: COLORS.mint, alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  userNickname: { fontSize: 14, fontWeight: '700', color: COLORS.ink },
  userEmail: { fontSize: 11.5, color: COLORS.inkMuted48 },
  statusChip: { paddingVertical: 3, paddingHorizontal: 9, borderRadius: RADIUS.pill },
  statusChipText: { fontSize: 10.5, fontWeight: '700' },
  bottomNav: { flexDirection: 'row', justifyContent: 'space-around', paddingTop: 10, paddingBottom: 20, borderTopWidth: 1, borderTopColor: COLORS.hairline, backgroundColor: 'rgba(255,255,255,0.7)' },
  navItem: { alignItems: 'center', gap: 4, width: 76 },
  navLabel: { fontSize: 10, color: COLORS.inkMuted48 },
  toast: { position: 'absolute', left: '50%', bottom: 56, transform: [{ translateX: -100 }], backgroundColor: COLORS.ink, borderRadius: RADIUS.pill, paddingVertical: 12, paddingHorizontal: 20 },
  toastText: { color: '#fff', fontSize: 13, fontWeight: '600' },
  sheetOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(3,50,54,0.45)' },
  sheet: { backgroundColor: '#fff', borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, paddingBottom: 26, gap: 16 },
  sheetHandle: { width: 36, height: 4, borderRadius: 9999, backgroundColor: 'rgba(0,0,0,0.12)', alignSelf: 'center' },
  detailNickname: { fontSize: 17, fontWeight: '700', color: COLORS.ink },
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  statBox: { width: '47.5%', backgroundColor: COLORS.parchment, borderRadius: 14, padding: 12, paddingHorizontal: 14 },
  statLabel: { fontSize: 11.5, color: COLORS.inkMuted48, fontWeight: '600' },
  statValue: { fontSize: 14.5, fontWeight: '700', color: COLORS.ink, marginTop: 4 },
  warnButton: { flex: 1, height: 48, borderRadius: RADIUS.pill, backgroundColor: COLORS.parchment, borderWidth: 1, borderColor: COLORS.hairline, alignItems: 'center', justifyContent: 'center' },
  warnButtonText: { fontSize: 14.5, fontWeight: '700', color: COLORS.ink },
  suspendButton: { flex: 1, height: 48, borderRadius: RADIUS.pill, alignItems: 'center', justifyContent: 'center' },
  suspendButtonText: { fontSize: 14.5, fontWeight: '700', color: '#fff' },
});
