import { StyleSheet } from 'react-native';
import { COLORS, RADIUS } from '../../../shared/디자인/tokens';


export const styles = StyleSheet.create({
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 4, flexDirection: 'row', alignItems: 'center', gap: 8 },
  logoBadge: { width: 30, height: 30, borderRadius: 9, backgroundColor: COLORS.primary, alignItems: 'center', justifyContent: 'center' },
  logo: { fontSize: 20, fontWeight: '700', color: COLORS.primary },
  adminTag: { backgroundColor: COLORS.goldTint, borderWidth: 1, borderColor: 'rgba(201,162,39,0.5)', paddingVertical: 3, paddingHorizontal: 9, borderRadius: RADIUS.pill },
  adminTagText: { fontSize: 11, fontWeight: '800', color: COLORS.primary },
  content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 22, gap: 18 },
  kpiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  kpiCard: { width: '47.5%', backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 16, padding: 14 },
  kpiLabel: { fontSize: 12, color: COLORS.inkMuted48, fontWeight: '600' },
  kpiValue: { fontSize: 19, fontWeight: '700', color: COLORS.ink, marginTop: 6 },
  kpiDelta: { fontSize: 11, fontWeight: '700', marginTop: 5 },
  shortcutGreen: { flex: 1, height: 46, borderRadius: 14, backgroundColor: '#E3F5E7', borderWidth: 1, borderColor: 'rgba(3,50,54,0.12)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  shortcutGold: { flex: 1, height: 46, borderRadius: 14, backgroundColor: COLORS.goldTint, borderWidth: 1, borderColor: 'rgba(201,162,39,0.25)', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6 },
  shortcutText: { fontSize: 13.5, fontWeight: '700', color: COLORS.primary },
  sectionHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  sectionTitle: { fontSize: 15, fontWeight: '700', color: COLORS.ink },
  seeAll: { fontSize: 12, fontWeight: '600', color: COLORS.inkMuted48 },
  listCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 16, overflow: 'hidden' },
  userRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 11, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: 'rgba(0,0,0,0.05)' },
  avatar: { width: 32, height: 32, borderRadius: 9999, backgroundColor: COLORS.mint, alignItems: 'center', justifyContent: 'center' },
  avatarText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  userNickname: { fontSize: 13.5, fontWeight: '700', color: COLORS.ink },
  userEmail: { fontSize: 11.5, color: COLORS.inkMuted48 },
  statusChip: { paddingVertical: 3, paddingHorizontal: 9, borderRadius: RADIUS.pill },
  statusChipText: { fontSize: 10.5, fontWeight: '700' },
  reportCard: { backgroundColor: '#fff', borderWidth: 1, borderColor: COLORS.hairline, borderRadius: 16, padding: 12, paddingHorizontal: 14, gap: 6 },
  typeTag: { backgroundColor: '#FBEAE8', paddingVertical: 3, paddingHorizontal: 9, borderRadius: RADIUS.pill },
  typeTagText: { fontSize: 11, fontWeight: '700', color: '#B23A34' },
  reportDate: { fontSize: 11, color: COLORS.inkMuted48 },
  reportTarget: { fontSize: 13.5, fontWeight: '700', color: COLORS.ink },
  reportReason: { fontSize: 12, color: COLORS.inkMuted48, lineHeight: 16 },
  bottomNav: { flexDirection: 'row', justifyContent: 'space-around', paddingTop: 10, paddingBottom: 20, borderTopWidth: 1, borderTopColor: COLORS.hairline, backgroundColor: 'rgba(255,255,255,0.7)' },
  navItem: { alignItems: 'center', gap: 4, width: 76 },
  navLabel: { fontSize: 10, color: COLORS.inkMuted48 },
});
